[package]
name = "ascii-generator"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
description = "An ascii image generator"
repository = "https://github.com/bstr1ckland/ascii-generator"
readme = "README.md"
keywords = ["ascii", "ascii-characters", "ascii-images", "first-crate"]
categories = ["ascii-images", "ascii-generation"]

[dependencies]
image = "0.25.10"
indoc = "2.0.7"
ndarray = "0.17.2"
